### ISSUE TITLE
request: info for 'STREAMLINED GLASS BUOYANCY PACKAGE'

### ISSUE THREAD

**Issue by dankelley** [dankelley/mooring#28]
In the BIO table of components (top part of the snapshot), I don't see anything that seems to match the name `STREAMLINED GLASS BUOYANCY PACKAGE` that is at the top of the mooring diagram (bottom part) for mooring 1840 (Greenan, Sackville Spur, July 2013).

@formulafunracing or @clayton33: Any idea what I should use for buoyancy, height, area, and CD?

PS: I ask because I want to simulate that mooring.

<img width="1052" alt="Screen Shot 2021-06-11 at 5 46 33 AM" src="https://user-images.githubusercontent.com/99469/121659699-ef9f1a80-ca78-11eb-9754-2cf292604a36.png">

**Comment by FormulaFunRacing** [comment]
Hi Dan

I should have updated our table.  It's the 'original' name in the table...'STREAMLINED BUB 2 x 17" GLASS'.  It really should be re-labelled as an Open Seas C2 SUBS package.   Actually, I need to look at this because I notice the 'NEW GLASS STREAMINED FLOAT (C2)' just above it in the table.  Also, the AW (0.164) doesn't look right for the 'STREAMLINED BUB 2 x 17" GLASS'.  (I can't believe I'm just noticing this now.  The table was started many years ago by my predecessor...probably as a Quattro Pro file.  I need to grab a pack of cigarettes and a large ashtray, to go through this table...).

For now, I would use the numbers in 'NEW GLASS STREAMINED FLOAT (C2)', with 100 lbf [445 N].  This is the Open Seas C2 SUBS float.  The 'STREAMLINED BUB 2 x 17" GLASS' might be from a handful of prototypes we had made, tested and used.

**Comment by dankelley** [comment]
I'll close this, since I have the info I requested. Thanks, @FormulaFunRacing!
