### ISSUE TITLE
shallow moorings (< 2 m)

### ISSUE THREAD

**Issue by dempsey-CMAR** [dankelley/mooring#47]
Hello, 

As discussed last week, I am wondering if the package can handle relatively shallow moorings (e.g., water depth is ~ 2 m, wire length is ~ 1.5 m).

**Comment by dankelley** [comment]
Can you tell me the wire type, and the float and instrument types?  If they are in the known list, then we can do it easily. Otherwise, we'd need to know the buoyancy of each item, the area for instrument and float, the width of wire, etc.

To see the known types, you can do e.g.
```R
library(mooring)
wire("?")
instrument("?")
float("?")
```

**Comment by dankelley** [comment]
The package can handle short moorings.  I show that in the reprex given below (a reprex is created with `reprex::reprex()`, which is *very* handy).

I do a lot of other stuff also.  I first tried using a concrete-block anchor from the built-in anchor types, but it has a stated height of 0.5m, which seem crazy.  (I don't know what kind of block they are talking about but jeeze...)

I show some other stuff as well, e.g.

1. I am creating a new anchor type.
2. You can see that the `discretise()` call has broken it up the wire into 10-cm pieces. I'd need to think about why the plot is so piecewise linear, but I don't doubt it.  (Basically, this microcat must create a fair bit of drag force.)
3. There is a bug in plotting.  The gray line is the mooring in zero current. Note that it starts at some distance above the bottom, because of the anchor.  (Maybe I should use a black box for the anchor.). But the error is that the dark line, i.e. the knocked-over mooring, is drawn from the bottom.  I'll make an issue on that.

``` r
u <- 2 # current speed
library(mooring)

# Display build-in anchors
anchor("?")
#>  [1] "1 Concrete Block"  "1 Large St/C Tire" "1 Railway Wheel"  
#>  [4] "1 Tire-St+Con"     "2 Concrete Blocks" "2 Railway Wheels" 
#>  [7] "3 Concrete Blocks" "3 Railway Wheels"  "3 trainwheels"    
#> [10] "4 Railway Wheels"

# Show that the concrete block anchor is specified to have
# a very high height ...
anchor("1 Concrete Block") # height 0.5m, which seems crazy to me!
#> 1: "1 Concrete Block" anchor, -200kg, height 0.5m, in 0m water depth

# ... create a new anchor.  This is set to be something two
# humans could easily handle.  Dunno what, though! This does
# not matter much.  We will want buoyancy that can fight the
# float, whatever that is, but so long as that is satisfied,
# all that matters is the height.  (We have to supply CD,
# but it is not used.) Note how I'm making a function for this,
# so we can use it generally.
A <- function(depth) {
    anchor("my anchor",
        buoyancy = -50, height = 0.2, CD = 0,
        depth = depth
    )
}

# Create a mooring in 2 m of water.
m <- mooring(
    A(2), # user-created anchor in 2m of water
    wire(length = 0.3),
    instrument("SBE37 microcat clamp-on style"),
    wire(length = 0.2),
    float("HMB 20")
)

# Break wire up into subcomponents 0.1 m long.
md <- discretise(m, by = 0.1)

# Compute mooring shape with a 1 m/s current.
mdk <- knockdown(md, u = u)

# Show mooring shape in that current
plot(mdk)
```

![](https://i.imgur.com/QUAJBQc.png)

``` r

# Show components. Expectation: 2 subcomponents between microcat
# and float, and 3 subcomponents between anchor and microcat.
for (i in seq_along(md))
{
    print(md[[i]])
}
#> 1: "HMB 20" float, 34.5kg, height 0.508m, area 0.2027m^2
#> 1: "1/4in wire/jack" wire, -0.013kg, length 0.1m, area 0.0008m^2
#> 1: "1/4in wire/jack" wire, -0.013kg, length 0.1m, area 0.0008m^2
#> 1: "SBE37 microcat clamp-on style" instrument, -1.53kg, area 0.117m^2
#> 1: "1/4in wire/jack" wire, -0.013kg, length 0.1m, area 0.0008m^2
#> 1: "1/4in wire/jack" wire, -0.013kg, length 0.1m, area 0.0008m^2
#> 1: "1/4in wire/jack" wire, -0.013kg, length 0.1m, area 0.0008m^2
#> 1: "my anchor" anchor, -50kg, height 0.2m, in 2m water depth

# Show that summary() joins up wire subcomponents.
summary(md)
#> 1: "HMB 20" float, 34.5kg, height 0.508m, area 0.2027m^2
#> 1: "1/4in wire/jack" wire, -0.013kg, length 0.2m, area 0.0008m^2
#> 1: "SBE37 microcat clamp-on style" instrument, -1.53kg, area 0.117m^2
#> 1: "1/4in wire/jack" wire, -0.013kg, length 0.3m, area 0.0008m^2
#> 1: "my anchor" anchor, -50kg, height 0.2m, in 2m water depth
```

<sup>Created on 2023-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
Oh, that makes sense re the block.  Thanks!

**Comment by dankelley** [comment]
@dempsey-CMAR I think this works OK now; for an example, see https://github.com/dankelley/mooring/issues/49#issuecomment-1848417142 (which is in a now-closed issue).

If you agree that this issue has been addressed, please add a brief comment and close it.  Otherwise, please add a comment (brief or not -- your choice!) that explains what remains to be done.

In this project, as with the `oce` project, we rely on reporters to decide whether an issue is to be close.  The developers only close issues if discussion has ended and the issue has been addressed (in the opinion of the developers).

**Comment by dankelley** [comment]
Further note: most (maybe all) `instrument` objects have a nonzero `height` parameter.  That causes problems for shallow moorings, so I created a new function named `clamped()` to designate that the instrument is clamped on to the wire, contributing nothing to the total length of the mooring.

This is done in commit 7b50bafe46617fe9d563768b72dc7bd3dea52971  of "main".  To see why it matters for very shallow moorings, see the plots (and code) at https://dankelley.github.io/mooring/reference/clamped.html.

**Comment by dempsey-CMAR** [comment]
Wow thanks for all of this! I will take a closer look next week and close the Issue.

**Comment by dankelley** [comment]
@dempsey-CMAR it might make sense to have a meeting so I can explain some new things.  We can arrange that over email -- I don't like scheduling things or giving any personal details on github.

**Comment by dankelley** [comment]
@dempsey-CMAR Do you think this issue -- as defined by its title -- has been addressed?  If so, please close this issue.  If not, please add a comment explaining what remains to be done.

PS. the main thing is that the code now will subdivide "wire" components into sub-metre portions.  I don't actually think that will matter much because the catenary shape may be mostly straight for short wires.

PPS. I'm partly asking for feedback because I am trying to debug why github is no longer sending me emails when issues change.  So if you may any comment, even just entering a "." character, that would be great.

**Comment by dempsey-CMAR** [comment]
Hi @dankelley, thank for following up with this. Yes I think this issue has been addressed and I will close it. We are hoping to play around with the package more in the spring, so I will open a new issue if we notice anything strange.

**Comment by dankelley** [comment]
Excellent, thanks so much.  And remember, we can meet anytime, if you folks want to start using the package and think of new features (or find bugs).
